workflows:
    trigger:
      name: trigger builds for different branches
      environment:
        groups:
          - firebase_credentials
          - google_play_credentials2
          - token
      scripts:
        - name: Trigger multiple client builds
          script: |
            WORKFLOW="android-workflow"  # Replace with your workflow ID
            APP_ID="645a0fafc5f77d006a400bf1"  # Replace with your App ID

            # Define an array of branch names
            BRANCHES=("main" "master" "dev")

            for BRANCH in ${BRANCHES[@]}; do
              echo "Triggering workflow $WORKFLOW for branch $BRANCH"

              Make the POST request to trigger the build for the current branch
              curl -H "Content-Type: application/json" -H "x-auth-token: $CM_API_KEY" \
                --data '{
                  "appId": "645a0fafc5f77d006a400bf1",
                  "workflowId": "android-workflow",
                  "branch": "'${BRANCH}'",
                  "environment": {
                      "variables": {
                          "PACKAGE_NAME": "io.codemagic.dtrdic6"
                      }
                  }
                }' \
                https://api.codemagic.io/builds
            done

    android-workflow:
        name: Android Workflow
        max_build_duration: 120
        instance_type: mac_mini_m1
        environment:
          flutter: 3.16.0-beta
          android_signing: 
            - testKeystore
          groups:
            - shorebird_token
            - firebase_credentials 
            - google_credentials3
          vars:
            PACKAGE_NAME: "io.codemagic.dtrdic6"
            GOOGLE_PLAY_TRACK: internal 
        triggering:
          events:
              - pull_request 
          branch_patterns: 
          - pattern: "TestPR3" #test
            include: true 
            source: false
        # when:
        #   condition: (not event.pull_request.draft) and not (event.pull_request.head.ref == "TestPR")

        scripts:
          - name: flutter version
            script: |
              flutter --version
          - name: Set up local.properties
            script: |
              echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
          - name: Get Flutter packages
            script: |
              flutter packages pub get
          - name: Build AAB with Flutter
            script: |
              LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))
              if [ -z $LATEST_GOOGLE_PLAY_BUILD_NUMBER ]; then
                UPDATED_BUILD_NUMBER=$BUILD_NUMBER
              else
                UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
              fi
              flutter build appbundle --release \
                --build-name=1.0.$UPDATED_BUILD_NUMBER \
                --build-number=$UPDATED_BUILD_NUMBER
                # --obfuscate \
                # --split-debug-info \
                #ovaj obsuficate napravi 3 fajla(debug symbols) u Clone/debug-info floder 
          - name: Launch Custom Android Emulator
            script: | 
                export PATH="$PATH":"$ANDROID_HOME/cmdline-tools/latest/bin"
                echo y | sdkmanager "system-images;android-33;google_apis;x86_64"
                echo no | avdmanager create avd -n emulator -k "system-images;android-33;google_apis;x86_64" --name "EWEGO_EMUL_API_33" -n Android33 --package "system-images;android-33;google_apis;x86_64" --tag "google_apis" --device "Galaxy Nexus"

                emulator -memory 2048 -avd Android33 -no-audio -gpu swiftshader_indirect -debug-init -wipe-data &   
                adb wait-for-device
          # - name: Rename the apk file
          #   script: | 
          #     mv build/**/outputs/**/*.aab \
          #       build/**/outputs/**/app-release-renamed.aab
        artifacts:
          - build/**/outputs/**/*.aab
          - build/**/outputs/**/app-release-renamed.aab
          - build/**/outputs/**/mapping.txt
          - flutter_drive.log
          - debug-info.zip
        publishing:
          # firebase:
          #     firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
          #     android:
          #       app_id: 1:701760780130:android:78886c544e828688f09e3b
          email:
            recipients:
              - david@nevercode.io
          google_play:
            credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS3
            track: internal
            changes_not_sent_for_review: true
            submit_as_draft: true


    ios-workflow:
      name: iOS Workflow
      instance_type: mac_mini_m1
      max_build_duration: 120
      integrations:
        app_store_connect: DavidAPIkey 
      environment:
        xcode: 15
        #flutter: fvm
        ios_signing:
          distribution_type: app_store
          bundle_identifier: io.codemagic.dtrdic6
        groups:
            - test_device
            - firebase_credentials
        vars:
          APP_ID: 6450783332 # <-- Put your APP ID here 
      # triggering:
      #     events:
      #         - push
      #         - tag
      #     branch_patterns:
      #       - pattern: main, test
      #     cancel_previous_builds: true
      scripts:
        # - name: java 17 install
        #   script: |
        #     brew update
        #     brew install openjdk@17
        #     java --version
        # - name: set Java 17 as default
        #   script: |
        #     echo 'export JAVA_HOME="/usr/local/opt/openjdk@17"' >> ~/.zshrc
        #     echo 'export PATH="/usr/local/opt/openjdk@17/bin:$PATH"' >> ~/.zshrc
        # - name: java version
        #   script: |
        #     source ~/.zshrc
        #     java --version
        # - name: brew install 16
        #   script: |
        #     brew install node@16
        #     brew unlink node
        #     brew link --force --overwrite node@16
        #     node --version
        - name: Set up code signing settings on Xcode project 
          script: |
            xcode-project use-profiles
        - name: Get Flutter packages
          script: | 
            flutter packages pub get
        - name: Install pods
          script: | 
            find . -name "Podfile" -execdir pod install \;
        # - name: Run tests
        #   script: | 
        #     xcode-project run-tests \
        #     --workspace "ios/Runner.xcworkspace" \
        #     --scheme "Runner" \
        #     --device "$TEST_DEVICE" \
        #     --test-flags="-quiet"
        - name: Flutter build ipa and automatic versioning
          script: |
            agvtool new-version -all $(($BUILD_NUMBER + 1))
            flutter build ipa --release --flavor free \
              --build-name=1.0.$BUILD_NUMBER \
              --build-number=$BUILD_NUMBER \
              --export-options-plist=/Users/builder/export_options.plist
      artifacts:
        - /tmp/xcodebuild_logs/*.log
        - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
        - build/ios/ipa/*.ipa
        - flutter_drive.log
        - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
      publishing:
        email:
          recipients:
            - david@nevercode.io
          notify:
            success: true # To receive a notification when a build succeeds
            failure: false # To not receive a notification when a build fails
        app_store_connect:
          auth: integration 
          submit_to_testflight: false
          submit_to_app_store: true
          #submit_to_app_store: true #test2
        # firebase:
        #     firebase_service_account: $FIREBASE_SERVICE_ACCOUNT 
        #     ios:
        #       app_id: 1:701760780130:ios:d06fc5333b7c4ed3f09e3b
        # google_play:
        #     credentials: $GOOGLE_APPLICATION_CREDENTIALS
        #     track: internal
        scripts:
            - name: Upload debug symbols to Firebase Crashlytics
              script: | 
                echo "Find build artifacts"
                dsymPath=$(find $CM_BUILD_DIR/build/ios/archive/Runner.xcarchive -name "Runner.app.dSYM")
                if [[ -z ${dsymPath} ]]
                then
                  echo "No debug symbols were found, skip publishing to Firebase Crashlytics"
                else
                  echo "Publishing debug symbols from $dsymPath to Firebase Crashlytics"
                  ls -d -- ios/Pods/*
                  $CM_BUILD_DIR/ios/Pods/FirebaseCrashlytics/upload-symbols -gsp ios/Runner/GoogleService-Info.plist -p ios $dsymPath
                fi

    shorebird-workflow: 
        name: shorebird Workflow
        max_build_duration: 120
        instance_type: mac_mini_m1
        labels:
          - ${PACKAGE_NAME}
        environment:
          #flutter: fvm
          android_signing:
            - testKeystore
          groups:
            - shorebird_token
            - firebase_credentials
            - google_credentials3
          vars:
            PACKAGE_NAME: "io.codemagic.dtrdic6"
            GOOGLE_PLAY_TRACK: internal
        scripts:
          - name: Build aab
            script: | 
                flutter build appbundle 
          - name: ðŸ¦ Setup Shorebird
            script: |
              # Install Shorebird
              curl --proto '=https' --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | bash

              # Add Shorebird to PATH
              echo PATH="$HOME/.shorebird/bin:$PATH" >> $CM_ENV
          - name: ðŸš€ Shorebird INIT
            script:  shorebird init
          - name: ðŸš€ Shorebird release
            script:  shorebird release android
          - name: ðŸš€ Shorebird Patch
            script:  shorebird patch android --force
        
        artifacts:
          - build/**/outputs/**/*.aab
          - build/**/outputs/**/mapping.txt
          - flutter_drive.log
          - debug-info.zip
        publishing:
          # firebase:
          #     firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
          #     android:
          #       app_id: 1:701760780130:android:78886c544e828688f09e3b
          email:
            recipients:
              - david@nevercode.io
          google_play:
            credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS3
            track: internal
            changes_not_sent_for_review: true
            submit_as_draft: true

    windows-android-workflow:
        name: Windows publish Android Workflow
        max_build_duration: 120
        instance_type: windows_x2
        environment:
          android_signing:
            - testKeystore
          groups:
            - windows_credentials
            - google_credentials3
            - aws_credentials
        # triggering:
        #   events:
        #       - push
        #   branch_patterns:
        #   - pattern: "main"
        #     include: true
        #     source: false          
        scripts:
          - name: Get Flutter packages
            script: | 
                flutter packages pub get
          - name: Configure for Windows
            script: flutter config --enable-windows-desktop

          - name: install aws cli
            script: pip3 install awscli --upgrade

          - name: Aws version
            script: aws --version
          - name: Create a random file
            script: dd if=/dev/urandom of=sample2.txt bs=8M count=1
          - name: upload to aws bucket
            script: aws s3 cp sample2.txt s3://dtrdic-bucket/
          
          - name: Build Windows
            script: flutter build windows
          - name: Package Windows
            script: flutter pub run msix:create
          - name: Package Windows
            script: |
              flutter pub add msix
              flutter pub run msix:create --display-name='FlutterFvm' --publisher-display-name='FlutterFvm' --publisher='PublisherID' --identity-name='gizard.FlutterFVM' --version=1.0.0.0 --store=true
        
        artifacts:
          - build/windows/**/*.msix
        publishing:
          partner_center:
            store_id: $APP_ID # <-- You can find the `store_id` inside your Partner Center app by going to [Product management > Product Identity].
            tenant_id: $TENANT_ID # <-- You will get `tenant_id` from the Azure AD Overview page.
            client_id: $CLIENT_ID # <-- You will also get `client_id` from the Azure AD Overview page.
            client_secret: $CLIENT_SECRET # <-- `client_secret` is retrieved from the application environment variable
          email:
            recipients:
              - david@nevercode.io #test3

    discord-workflow:
      name: Discord integration Workflow
      instance_type: mac_mini_m1
      max_build_duration: 60
      environment:
        android_signing:
          - testKeystore
        groups:
          - discord_credentials 
        flutter: stable
        cocoapods: default 
      # triggering:
      #   events:
      #     - push
      scripts:        
        - name: set up local properties
          script: |
            echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
        - name: Get packages and build debug apk
          script: |
            flutter packages pub get && flutter build apk --debug
        - name: Create a changelog
          script: |
              if [[ -z ${CM_PREVIOUS_COMMIT} ]]
              then
                echo "No finished builds found to generate changelog" | tee release_notes.txt
              else
                echo "$(git-changelog generate --previous-commit $CM_PREVIOUS_COMMIT)" | tee release_notes.txt
              fi      
        - name:  exit code 1
          script: |
            exit code 1
      artifacts:
        - build/**/outputs/**/*.apk
        - build/**/outputs/**/*.aab
        - build/**/outputs/**/mapping.txt
        - flutter_drive.log
      publishing:
        scripts:
        - name: Discord notification
          script: |
            if [[ $CM_BUILD_STEP_STATUS == "failure" ]]; then
              # Handle the error case here
              echo "Here is the message for the failing step"
            else
              # Send the Discord notification as you did before
              set -ex

              APP_LINK=$(echo $CM_ARTIFACT_LINKS | jq -r '.[] | select(.name=="app.apk") | .url')

              # Get first 7 digits of commit number
              COMMIT=$(echo "${CM_COMMIT}" | sed 's/^\(........\).*/\1/;q')

              # Get commit message
              COMMIT_MESSAGE=$(git log --format=%B -n 1 $CM_COMMIT)

              # Get commit author
              AUTHOR=$(git show -s --format='%ae' $CM_COMMIT)

              curl -H "Content-Type: multipart/form-data" \
              -F 'payload_json={"username" : "codemagic-bot", "content": "**Commit:** `'"$COMMIT"'`\n\n**Commit message:** '"$COMMIT_MESSAGE"'\n\n**Branch:** '"$CM_BRANCH"'\n\n**Author:** '"$AUTHOR"'\n\n**Artifacts: **\n\n'"$APP_LINK"'\n\n"}' \
              -F "file1=@release_notes.txt" \
              $WEBHOOK_URL
            fi
          
        email:
          recipients:
            - david@nevercode.io

    watchOS-workflow:
      name: iOS Workflow
      instance_type: mac_mini_m1
      max_build_duration: 120
      integrations:
        app_store_connect: DavidAPIkey 
      environment:
        xcode: 15
        #flutter: fvm
        ios_signing:
          distribution_type: app_store
          bundle_identifier: io.codemagic.dtrdic6
        groups:
            - test_device
            - firebase_credentials
        vars:
          APP_ID: 6450783332 # <-- Put your APP ID here 
      # triggering:
      #     events:
      #         - push
      #         - tag
      #     branch_patterns:
      #       - pattern: main, test
      #     cancel_previous_builds: true
      scripts:
        # - name: java 17 install
        #   script: |
        #     brew update
        #     brew install openjdk@17
        #     java --version
        # - name: set Java 17 as default
        #   script: |
        #     echo 'export JAVA_HOME="/usr/local/opt/openjdk@17"' >> ~/.zshrc
        #     echo 'export PATH="/usr/local/opt/openjdk@17/bin:$PATH"' >> ~/.zshrc
        # - name: java version
        #   script: |
        #     source ~/.zshrc
        #     java --version
        # - name: brew install 16
        #   script: |
        #     brew install node@16
        #     brew unlink node
        #     brew link --force --overwrite node@16
        #     node --version
        - name: Set up code signing settings on Xcode project 
          script: |
            xcode-project use-profiles
        - name: Get Flutter packages
          script: | 
            flutter packages pub get
        - name: Install pods
          script: | 
            find . -name "Podfile" -execdir pod install \;
        # - name: Run tests
        #   script: | 
        #     xcode-project run-tests \
        #     --workspace "ios/Runner.xcworkspace" \
        #     --scheme "Runner" \
        #     --device "$TEST_DEVICE" \
        #     --test-flags="-quiet"
        - name: Flutter build ipa and automatic versioning
          script: |
            agvtool new-version -all $(($BUILD_NUMBER + 1))
            flutter build ipa --release --flavor free \
              --build-name=1.0.$BUILD_NUMBER \
              --build-number=$BUILD_NUMBER \
              --export-options-plist=/Users/builder/export_options.plist
      artifacts:
        - /tmp/xcodebuild_logs/*.log
        - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
        - build/ios/ipa/*.ipa
        - flutter_drive.log
        - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
      publishing:
        email:
          recipients:
            - david@nevercode.io
          notify:
            success: true # To receive a notification when a build succeeds
            failure: false # To not receive a notification when a build fails
        app_store_connect:
          auth: integration 
          submit_to_testflight: false
          submit_to_app_store: true
          #submit_to_app_store: true #test2
        # firebase:
        #     firebase_service_account: $FIREBASE_SERVICE_ACCOUNT 
        #     ios:
        #       app_id: 1:701760780130:ios:d06fc5333b7c4ed3f09e3b
        # google_play:
        #     credentials: $GOOGLE_APPLICATION_CREDENTIALS
        #     track: internal
        scripts:
            - name: Upload debug symbols to Firebase Crashlytics
              script: | 
                echo "Find build artifacts"
                dsymPath=$(find $CM_BUILD_DIR/build/ios/archive/Runner.xcarchive -name "Runner.app.dSYM")
                if [[ -z ${dsymPath} ]]
                then
                  echo "No debug symbols were found, skip publishing to Firebase Crashlytics"
                else
                  echo "Publishing debug symbols from $dsymPath to Firebase Crashlytics"
                  ls -d -- ios/Pods/*
                  $CM_BUILD_DIR/ios/Pods/FirebaseCrashlytics/upload-symbols -gsp ios/Runner/GoogleService-Info.plist -p ios $dsymPath
                fi
