// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPWlt6EnVaTENfcKLa9cTQg7nmqC6u5uM',
    appId: '1:904035439120:web:61d76ca1365d9da0dfb095',
    messagingSenderId: '904035439120',
    projectId: 'flutterfvm',
    authDomain: 'flutterfvm.firebaseapp.com',
    storageBucket: 'flutterfvm.appspot.com',
    measurementId: 'G-FV90F3DWR3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGWGFJ2i-PpXIMYdwYKVcw28xJq19BZqM',
    appId: '1:904035439120:android:6b987f5e2e4b38a7dfb095',
    messagingSenderId: '904035439120',
    projectId: 'flutterfvm',
    storageBucket: 'flutterfvm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpKKyL27qkO-zsAgFFFPl5o5tQjBtqOHc',
    appId: '1:904035439120:ios:c3c4c406ed53ea64dfb095',
    messagingSenderId: '904035439120',
    projectId: 'flutterfvm',
    storageBucket: 'flutterfvm.appspot.com',
    iosClientId: '904035439120-4hmv6ds993t12kv8l4genlucdofrumen.apps.googleusercontent.com',
    iosBundleId: 'io.codemagic.dtrdic6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpKKyL27qkO-zsAgFFFPl5o5tQjBtqOHc',
    appId: '1:904035439120:ios:feeb21c667781fabdfb095',
    messagingSenderId: '904035439120',
    projectId: 'flutterfvm',
    storageBucket: 'flutterfvm.appspot.com',
    iosClientId: '904035439120-8pp1hgav91c0nlam2jg7m3or0i1k4vcp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFvm',
  );
}
