// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9hhvPSbbRULsL6WfzN9gJPI0PFf1rjZs',
    appId: '1:701760780130:web:f714be931719c52cf09e3b',
    messagingSenderId: '701760780130',
    projectId: 'pc-api-8478664491092592353-718',
    authDomain: 'pc-api-8478664491092592353-718.firebaseapp.com',
    storageBucket: 'pc-api-8478664491092592353-718.appspot.com',
    measurementId: 'G-T4ZXW7YY4V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDtx511F15LUvcXvf3x4SZFxU1HyUTm24',
    appId: '1:701760780130:android:78886c544e828688f09e3b',
    messagingSenderId: '701760780130',
    projectId: 'pc-api-8478664491092592353-718',
    storageBucket: 'pc-api-8478664491092592353-718.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA15RREmOHuFAMx8F1-RgzD84Qv_9gs7dU',
    appId: '1:701760780130:ios:d06fc5333b7c4ed3f09e3b',
    messagingSenderId: '701760780130',
    projectId: 'pc-api-8478664491092592353-718',
    storageBucket: 'pc-api-8478664491092592353-718.appspot.com',
    iosClientId: '701760780130-17omlk3eii4llhm8aa6vc5mg4r9mlttm.apps.googleusercontent.com',
    iosBundleId: 'io.codemagic.dtrdic6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA15RREmOHuFAMx8F1-RgzD84Qv_9gs7dU',
    appId: '1:701760780130:ios:5f9b9e26a656280ff09e3b',
    messagingSenderId: '701760780130',
    projectId: 'pc-api-8478664491092592353-718',
    storageBucket: 'pc-api-8478664491092592353-718.appspot.com',
    iosClientId: '701760780130-70nu0r7ersc6n3nmk6d7sr9vle50lfgo.apps.googleusercontent.com',
    iosBundleId: 'io.codemagic.dtrdic6',
  );
}
